2017-05-25 21:59:01,366 logging_class.py[line:46] ERROR 'Data'
